
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    networks:
      - crack-network

  manager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_CMD: "cmd/manager"
    container_name: manager
    environment:
      PORT: ${INNER_SERVICE_PORT}
      WORKER_URLS: ${WORKER_URLS}
      MANAGER_TASK_TIMEOUT: ${MANAGER_TASK_TIMEOUT}
      MANAGER_WATCH_INTERVAL: ${MANAGER_WATCH_INTERVAL}
      READ_TIMEOUT: ${MANAGER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${MANAGER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${MANAGER_IDLE_TIMEOUT}
      CLIENT_TIMEOUT: ${MANAGER_CLIENT_TIMEOUT}
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_NAME: ${MONGODB_NAME}
    ports:
      - "${MANAGER_PORT}:${INNER_SERVICE_PORT}"
    depends_on:
      - mongo
    networks:
      - crack-network

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_CMD: "cmd/worker"
    container_name: worker1
    environment:
      PORT: ${WORKER_PORT}
      MANAGER_URL: ${MANAGER_URL}
      READ_TIMEOUT: ${WORKER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${WORKER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${WORKER_IDLE_TIMEOUT}
      CLIENT_TIMEOUT: ${WORKER_CLIENT_TIMEOUT}
      CONTEXT_CHECK_ITERATIONS: ${WORKER_CONTEXT_CHECK_ITERATIONS}
      STOP_ON_FIRST_MATCH: ${WORKER_STOP_ON_FIRST_MATCH}
    depends_on:
      - manager
    networks:
      - crack-network

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_CMD: "cmd/worker"
    container_name: worker2
    environment:
      PORT: ${WORKER_PORT}
      MANAGER_URL: ${MANAGER_URL}
      READ_TIMEOUT: ${WORKER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${WORKER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${WORKER_IDLE_TIMEOUT}
      CLIENT_TIMEOUT: ${WORKER_CLIENT_TIMEOUT}
      CONTEXT_CHECK_ITERATIONS: ${WORKER_CONTEXT_CHECK_ITERATIONS}
      STOP_ON_FIRST_MATCH: ${WORKER_STOP_ON_FIRST_MATCH}
    depends_on:
      - manager
    networks:
      - crack-network

  worker3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_CMD: "cmd/worker"
    container_name: worker3
    environment:
      PORT: ${WORKER_PORT}
      MANAGER_URL: ${MANAGER_URL}
      READ_TIMEOUT: ${WORKER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${WORKER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${WORKER_IDLE_TIMEOUT}
      CLIENT_TIMEOUT: ${WORKER_CLIENT_TIMEOUT}
      CONTEXT_CHECK_ITERATIONS: ${WORKER_CONTEXT_CHECK_ITERATIONS}
      STOP_ON_FIRST_MATCH: ${WORKER_STOP_ON_FIRST_MATCH}
    depends_on:
      - manager
    networks:
      - crack-network

networks:
  crack-network:
    driver: bridge