
services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_CMD: "cmd/manager"
    container_name: manager
    environment:
      PORT: ${INNER_SERVICE_PORT}
      WORKERS_URLS: ${WORKERS_URLS}
      MANAGER_MAX_TASKS_STORAGE: ${MANAGER_MAX_TASKS_STORAGE}
      MANAGER_TASK_TIMEOUT: ${MANAGER_TASK_TIMEOUT}
      MANAGER_WATCH_INTERVAL: ${MANAGER_WATCH_INTERVAL}
    ports:
      - "${MANAGER_PORT}:${INNER_SERVICE_PORT}"
    networks:
      - crack-network

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_CMD: "cmd/worker"
    container_name: worker1
    environment:
      MANAGER_URL: ${MANAGER_URL}
      READ_TIMEOUT: ${WORKER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${WORKER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${WORKER_IDLE_TIMEOUT}
      CLIENT_TIMEOUT: ${WORKER_CLIENT_TIMEOUT}
      CONTEXT_CHECK_INTERVAL: ${WORKER_CONTEXT_CHECK_INTERVAL}
      STOP_ON_FIRST_MATCH: ${WORKER_STOP_ON_FIRST_MATCH}
    depends_on:
      - manager
    networks:
      - crack-network

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_CMD: "cmd/worker"
    container_name: worker2
    environment:
      MANAGER_URL: ${MANAGER_URL}
      READ_TIMEOUT: ${WORKER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${WORKER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${WORKER_IDLE_TIMEOUT}
      CLIENT_TIMEOUT: ${WORKER_CLIENT_TIMEOUT}
      CONTEXT_CHECK_INTERVAL: ${WORKER_CONTEXT_CHECK_INTERVAL}
      STOP_ON_FIRST_MATCH: ${WORKER_STOP_ON_FIRST_MATCH}
    depends_on:
      - manager
    networks:
      - crack-network

  worker3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_CMD: "cmd/worker"
    container_name: worker3
    environment:
      MANAGER_URL: ${MANAGER_URL}
      READ_TIMEOUT: ${WORKER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${WORKER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${WORKER_IDLE_TIMEOUT}
      CLIENT_TIMEOUT: ${WORKER_CLIENT_TIMEOUT}
      CONTEXT_CHECK_INTERVAL: ${WORKER_CONTEXT_CHECK_INTERVAL}
      STOP_ON_FIRST_MATCH: ${WORKER_STOP_ON_FIRST_MATCH}
    depends_on:
      - manager
    networks:
      - crack-network

networks:
  crack-network:
    driver: bridge