
services:
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    command: ["--replSet", "${MONGODB_REPLICA_SET}", "--bind_ip_all"]
    ports:
      - "${MONGO_PRIMARY_EXT_PORT}:${MONGO_INNER_PORT}"
    networks:
      - crack-network

  mongo-secondary1:
    image: mongo:latest
    container_name: mongo-secondary1
    command: ["--replSet", "${MONGODB_REPLICA_SET}", "--bind_ip_all"]
    ports:
      - "${MONGO_SEC1_EXT_PORT}:${MONGO_INNER_PORT}"
    networks:
      - crack-network

  mongo-secondary2:
    image: mongo:latest
    container_name: mongo-secondary2
    command: ["--replSet", "${MONGODB_REPLICA_SET}", "--bind_ip_all"]
    ports:
      - "${MONGO_SEC2_EXT_PORT}:${MONGO_INNER_PORT}"
    networks:
      - crack-network

  mongo-setup:
    image: mongo:latest
    container_name: mongo-setup
    depends_on:
      - mongo-primary
      - mongo-secondary1
      - mongo-secondary2
    networks:
      - crack-network
    command: >
      bash -c "
        sleep 5;
        mongosh --host ${MONGO_PRIMARY} --eval '
          rs.initiate({
            _id: \"${MONGODB_REPLICA_SET}\",
            members: [
              { _id: 0, host: \"${MONGO_PRIMARY}\" },
              { _id: 1, host: \"${MONGO_SECONDARY1}\" },
              { _id: 2, host: \"${MONGO_SECONDARY2}\" }
            ]
          });
        ' || true;
        sleep 5;
      "

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - crack-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5

  manager:
    build:
      context: ../
      dockerfile: manager-service/Dockerfile
    container_name: manager
    environment:
      PORT: ${INNER_SERVICE_PORT}
      MANAGER_TASK_TIMEOUT: ${MANAGER_TASK_TIMEOUT}
      MANAGER_WATCH_INTERVAL: ${MANAGER_WATCH_INTERVAL}
      TASK_PARTS_COUNT: ${TASK_PARTS_COUNT}
      READ_TIMEOUT: ${MANAGER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${MANAGER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${MANAGER_IDLE_TIMEOUT}
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_NAME: ${MONGODB_NAME}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_TASKS_QUEUE: ${RABBITMQ_TASKS_QUEUE}
      RABBITMQ_RESULTS_QUEUE: ${RABBITMQ_RESULTS_QUEUE}
    ports:
      - "${MANAGER_PORT}:${INNER_SERVICE_PORT}"
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - crack-network

  worker1:
    build:
      context: ../
      dockerfile: worker-service/Dockerfile
    container_name: worker1
    environment:
      PORT: ${WORKER_PORT}
      READ_TIMEOUT: ${WORKER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${WORKER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${WORKER_IDLE_TIMEOUT}
      CONTEXT_CHECK_ITERATIONS: ${WORKER_CONTEXT_CHECK_ITERATIONS}
      STOP_ON_FIRST_MATCH: ${WORKER_STOP_ON_FIRST_MATCH}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_TASKS_QUEUE: ${RABBITMQ_TASKS_QUEUE}
      RABBITMQ_RESULTS_QUEUE: ${RABBITMQ_RESULTS_QUEUE}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - crack-network

  worker2:
    build:
      context: ../
      dockerfile: worker-service/Dockerfile
    container_name: worker2
    environment:
      PORT: ${WORKER_PORT}
      READ_TIMEOUT: ${WORKER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${WORKER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${WORKER_IDLE_TIMEOUT}
      CONTEXT_CHECK_ITERATIONS: ${WORKER_CONTEXT_CHECK_ITERATIONS}
      STOP_ON_FIRST_MATCH: ${WORKER_STOP_ON_FIRST_MATCH}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_TASKS_QUEUE: ${RABBITMQ_TASKS_QUEUE}
      RABBITMQ_RESULTS_QUEUE: ${RABBITMQ_RESULTS_QUEUE}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - crack-network

  worker3:
    build:
      context: ../
      dockerfile: worker-service/Dockerfile
    container_name: worker3
    environment:
      PORT: ${WORKER_PORT}
      READ_TIMEOUT: ${WORKER_READ_TIMEOUT}
      WRITE_TIMEOUT: ${WORKER_WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${WORKER_IDLE_TIMEOUT}
      CONTEXT_CHECK_ITERATIONS: ${WORKER_CONTEXT_CHECK_ITERATIONS}
      STOP_ON_FIRST_MATCH: ${WORKER_STOP_ON_FIRST_MATCH}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_TASKS_QUEUE: ${RABBITMQ_TASKS_QUEUE}
      RABBITMQ_RESULTS_QUEUE: ${RABBITMQ_RESULTS_QUEUE}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - crack-network

networks:
  crack-network:
    driver: bridge